name: risk-utils
version: 0.1.1
private: true
homepage: https://risk.techcable.net
dependencies:
  bootstrap: ^5.3.3
  next: ^15.2.4
  react: ^19.1.0
  react-bootstrap: ^2.10.9
  react-dom: ^19.1.0
scripts:
  preinstall: npx only-allow pnpm
  predeploy: pnpm run build
  # requires building typescript first (use just)
  dev: just dev
  build: just build
  start: just start
browserslist:
  production:
    - '>0.2%'
    - not dead
    - not op_mini all
  development:
    - last 1 chrome version
    - last 1 firefox version
    - last 1 safari version
devDependencies:
  '@types/react': ^19.0.12
  '@types/node': 22.13.14
  gh-pages: ^6.3.0
  typescript: 5.8.2
  prettier: ^3.5.3
